[package]
name = "enumset_test_no_std"
version = "0.0.0"
edition = "2021"

description = "DO NOT PUBLISH"
publish = false

[dependencies]
defmt = "1.0.1"
defmt-semihosting = "0.3.0"
enumset = { path = "../enumset", features = ["defmt"] }
