name: build

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        rustver: ["stable", "beta", "nightly"]
        args:
        - ""
        - "--features serde"
        - "--features alloc"
        - "--features proc-macro-crate"
        - "--features serde,alloc,proc-macro-crate"
        - "--release --features serde,alloc,proc-macro-crate"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: ${{ matrix.rustver }}
        default: true
    - uses: actions-rs/cargo@v1
      with:
        command: version
    - uses: actions-rs/cargo@v1
      with:
        command: test
        args: -p enumset ${{ matrix.args }}

  build_msrv:
    strategy:
      matrix:
        args: [ "", "--features serde", "--features alloc", "--release --features serde,alloc" ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: "1.61.0"
          default: true
      - uses: actions-rs/cargo@v1
        with:
          command: version
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: -p enumset ${{ matrix.args }}

  build_msrv_all_features:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: "1.69.0"
          default: true
      - uses: actions-rs/cargo@v1
        with:
          command: version
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: -p enumset --features serde,alloc,proc-macro-crate

  test_trybuild:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          default: true
          components: clippy
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: -p enumset_test_trybuild
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -p enumset_test_trybuild

  test_build_embedded:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        target: thumbv6m-none-eabi
        default: true
        components: clippy
    - uses: actions-rs/cargo@v1
      with:
        command: build
        args: --target thumbv6m-none-eabi -p enumset_test_embedded
    - uses: actions-rs/cargo@v1
      with:
        command: clippy
        args: --target thumbv6m-none-eabi -p enumset_test_embedded
