name: build

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        rustver: ["stable", "beta", "nightly"]
        args:
        - ""
        - "--features serde"
        - "--features alloc"
        - "--features proc-macro-crate"
        - "--features serde,alloc,proc-macro-crate"
        - "--release --features serde,alloc,proc-macro-crate"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - run: rustup toolchain install ${{ matrix.rustver }}
    - run: rustup override set ${{ matrix.rustver }}
    - run: cargo test -p enumset ${{ matrix.args }}

  build_msrv:
    strategy:
      matrix:
        args: [ "", "--features serde", "--features alloc", "--release --features serde,alloc", "--features serde,alloc,proc-macro-crate" ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: rustup toolchain install 1.83.0
      - run: rustup override set 1.83.0
      - run: cargo test -p enumset ${{ matrix.args }}

  test_nightly:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: rustup toolchain install nightly
      - run: rustup override set nightly
      - run: rustup component add clippy
      - run: cargo test -p enumset_test_nightly
      - run: cargo clippy -p enumset
      - run: cargo clippy -p enumset_test_nightly

  test_build_embedded:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - run: rustup toolchain install nightly
    - run: rustup override set nightly
    - run: rustup target install thumbv7em-none-eabihf
    - run: rustup component add clippy
    - uses: cachix/install-nix-action@v31
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - run: cargo build --target thumbv7em-none-eabihf -p enumset_test_embedded
    - run: cargo clippy --target thumbv7em-none-eabihf -p enumset_test_embedded
    - run: bash enumset_test_embedded/test_qemu_output.sh
