name: build

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        rustver: ["1.82.0", "stable", "beta", "nightly"]
        args_feature_set: [ "", "--features cfg_test_serde_nonmsrv_formats" ]
        args_configuration: [ "", "--features cfg_test_alloc", "--features cfg_test_proc-macro-crate", "--features cfg_test_alloc,cfg_test_proc-macro-crate" ]
        args_release: [ "", "--release" ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - run: rustup toolchain install ${{ matrix.rustver }}
    - run: rustup override set ${{ matrix.rustver }}
    - run: cargo test -p enumset_test ${{ matrix.args_release }} ${{ matrix.args_feature_set }} ${{ matrix.args_configuration }}

  build_msrv:
    strategy:
      matrix:
        args_feature_set: [ "", "--features cfg_test_serde" ]
        args_configuration: [ "", "--features cfg_test_alloc", "--features cfg_test_proc-macro-crate", "--features cfg_test_alloc,cfg_test_proc-macro-crate" ]
        args_release: [ "", "--release" ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: rustup toolchain install 1.71.0
      - run: rustup override set 1.71.0
      - run: cargo test -p enumset_test ${{ matrix.args_release }} ${{ matrix.args_feature_set }} ${{ matrix.args_configuration }}

  # TODO: Fix
  #test_nightly:
  #  runs-on: ubuntu-latest
  #  steps:
  #    - uses: actions/checkout@v5
  #    - run: rustup toolchain install nightly
  #    - run: rustup override set nightly
  #    - run: rustup component add clippy
  #    - run: cargo test -p enumset_test --features cfg_trybuild
  #    - run: cargo clippy -p enumset
  #    - run: cargo clippy -p enumset_test
  #    - run: cargo clippy -p enumset_test --features cfg_test_serde

  test_build_embedded:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - run: rustup toolchain install nightly
    - run: rustup override set nightly
    - run: rustup target install thumbv7em-none-eabihf
    - run: rustup component add clippy
    - uses: cachix/install-nix-action@v31
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - run: cargo build --target thumbv7em-none-eabihf -p enumset_test_embedded
    - run: cargo clippy --target thumbv7em-none-eabihf -p enumset_test_embedded
    - run: bash enumset_test_embedded/test_qemu_output.sh
